### PR TITLE
Offset analyzer dqm

### PR DESCRIPTION
**Pull request by cihar29**

### CODE REVIEW

**Comment by jpata** [comment]
Thanks, looks good! I will test tomorrow and merge unless there are issues.

**Comment by cihar29** [comment]
Thanks! Sorry I didn't test in the new framework. I'm making a couple minor changes

**Comment by jpata** [comment]
OK, let me know when it's tested and final from your side so I can give a try as well.

**Comment by cihar29** [comment]
All set!

**Comment by jpata** [comment]
Tested, works ✅

Right now, in addition to DQM histograms, it produces a standalone plot such as [stack_QCD.pdf](https://github.com/jpata/cmssw/files/2912502/stack_QCD.pdf).

Should we add something to the A vs B comparison script (`test/compare.py`), such that comparisons would end up on the [HTML page](http://hep.baylor.edu/hatake/PFval/val_10_4_Hcal8pulse/plots/FlatQCD_noPU_2018_pf.html)?

**Comment by cihar29** [comment]
I added the offset plotter to compare.py.
It's tough to write html using html.py since I don't use plotting.py.

I only need to create the html for the plots, but it will be cheesy because I will write the offset.html file inside compare.py.
This is the payoff of using an external plotting executable I guess, rather than plotting.py

**Comment by jpata** [comment]
Thanks @cihar29. I think the way you add the HTML currently is broken, see here for the produced output: http://jpata.web.cern.ch/jpata/pfvalidation/2019_02_28/plots/

The idea of the `compare.py` script is to take raw histograms directly from the DQM file and plot them like [this](http://hep.baylor.edu/hatake/PFval/val_10_4_Hcal8pulse/plots/FlatQCD_noPU_2018_ParticleFlow/reso_pt.pdf) automatically, all using the existing MultiTrackValidator comparison code. This way, the same output from two different runs of PFvalidation is on the same panel. So the raw histograms to be compared would be the different channels you store in the DQM code.

@hatakeyamak what do you think, any preference?

**Comment by hatakeyamak** [comment]
I probably need to understand what the issue is.
The comparisons of the stacked histograms are not supported by the current compare.py. If @
cihar29  has a script that can hadle it, we can adopt it just for these plots?

**Comment by jpata** [comment]
The existing MultiTrackValidator plot comparison code only compares single histograms between samples. The standalone C++ code by Chad produces a nice TDR-esque stack PDF plot from the various offset plots for a single sample, but we need to integrate it to the comparison code, one way or the other.

@cihar, can you take a look at the [HTML output](http://jpata.web.cern.ch/jpata/pfvalidation/2019_02_28/plots/)? I think there is a bug in your code as it just overwrites existing stuff (I didn't delve into it now). Otherwise we can revert the part that modifies the HTML and just keep the PDFs which need to be looked at manually by whoever is doing the study.

**Comment by hatakeyamak** [comment]
OK. I think it's nice to have a standard L1offset data-MC comparison style plots, where histograms are stacked, but comparisons are done for individual components.

But, if it's really tricky to have it in the  MultiTrackValidator plot comparison code, we can compare individual components I think.

**Comment by cihar29** [comment]
Sounds good I'll make the comparison for individual components using the plotting.py code.
I'll also add a little code to make the html for the tdr style all-component plots too.

**Comment by hatakeyamak** [comment]
Okay. Sounds good. Roughly what time scale do you think this will be achievable?

**Comment by cihar29** [comment]
Hopefully it will be ready in the next few hours (I was unavailable this weekend, my apologies)

**Comment by hatakeyamak** [comment]
Sounds great. Thank you.

**Comment by cihar29** [comment]
I updated a few things.
I follow the usual plotting for the individual components.
Then I add the tdr-style stack code separately.
Also, I added a 'Default' option to plotting.py that you may want to use

**Comment by cihar29** [comment]
To test, you can set
https://github.com/cihar29/cmssw/blob/offsetAnalyzerDQM/Validation/RecoParticleFlow/python/defaults_cfi.py#L31
to 3 (for QCD noPU sample), so there are less npv plots

**Comment by hatakeyamak** [comment]
Thanks. Do you have a link to the html and/or web page, which readily shows the plots you added?

**Comment by cihar29** [comment]
I view my plots directory with SimpleHTTPServer.
You could copy my plots dir:
/afs/cern.ch/work/c/charring/public/CMSSW_10_5_0_pre1/src/Validation/RecoParticleFlow/plots

I'm not sure how to set up a cern website :/
I'm attempting to set one up

**Comment by hatakeyamak** [comment]
OK. I put them here
http://hep.baylor.edu/hatake/PFval/Chad_20190305/plots/FlatQCD_noPU_offset.html
The error bars are very large. What is the definition of the error?

**Comment by cihar29** [comment]
I simply fill
https://github.com/cihar29/cmssw/blob/offsetAnalyzerDQM/Validation/RecoParticleFlow/plugins/OffsetAnalyzerDQM.cc#L201

I ran on only 500 events, so must be low statistics. Many eta bins and pftypes

**Comment by hatakeyamak** [comment]
You may need to do bookProfile with " " option, otherwise spread instead of the error may be used for the error bar. I don't know why. But, profile's default option in DQM is different from the root's profile
http://cmslxr.fnal.gov/source/DQMServices/Core/src/DQMStore.cc#1269

**Comment by cihar29** [comment]
Interesting thanks!
I updated my plots directory if you want to take a look

**Comment by hatakeyamak** [comment]
Thanks. I updated:
http://hep.baylor.edu/hatake/PFval/Chad_20190305/plots/FlatQCD_noPU_offset.html
The error looks more realistic I think.

**Pull request merged**
