### PR TITLE
Refactoring of PFAlgo [don't merge]

### PR DESCRIPTION
**Pull request by jpata**
I broke apart the big loop in `processBlock` in PFAlgo into smaller functions, as a first attempt to understand the flow of the code and in the future decouple the code from the global state.

Before the change, `PFAlgo::processBlock` was a function of ~3000 lines, now it is about 200 lines, and calls the following new functions (names kind of arbitrary):
 - `PFAlgo::photonAlgo`: ~40 lines
 - `PFAlgo::EGammaAlgo`: ~150 lines
 - `PFAlgo::conversionAlgo`: ~20 lines
 - `PFAlgo::EleLoop1`: ~400 lines
 - `PFAlgo::HFalgo`: ~100 lines
 - `PFAlgo::HCALLoop`: ~1300 lines
 - `PFAlgo::HCALUnlinkedLoop`: ~200 lines
 - `PFAlgo::ECALLoop`: ~40 lines

No attempt was made to change the dataformats or reliance on the global state, or to understand what is going on in the functions, just to break apart a big function into smaller ones to have a clearer view of what's going on.

Also ran `clang-format` on PFAlgo.cc as it was formatted extremely unreadably (this will be likely run on all CMSSW code at some point as I understand: https://github.com/cms-sw/cmssw/issues/26082)

It compiles and runs, physics validation ongoing.

Appreciate your comments
@hatakeyamak @bendavid @guitargeek @juska 

I made the PR here as opposed to cms-sw/cmssw in order to be able to to get first quick feedback if this is the direction the PF group wants to take, later we can port.

### CODE REVIEW

**Comment by hatakeyamak** [comment]
Will take a look, maybe over the weekend.
I think some new functions are not necessary after the legacy Run 1 code cleaning.

**Comment by jpata** [comment]
I've verified that I get the same PF output after this refactoring on 1000 events and looking at the DQM output as well as doing a diff between the PFAlgo verbose mode. Given that this is simply reshuffling the code from a big loop to separate contained functions with absolutely minimal modifications and no attempt at rewriting, this is expected.

I think after the code is split into manageable chunks with distinct responsibilities, we can look at which parts will be needed in the future, which should be rewritten better etc.

[response_10_24.pdf](https://github.com/jpata/cmssw/files/3168415/response_10_24.pdf)
[response_24_32.pdf](https://github.com/jpata/cmssw/files/3168421/response_24_32.pdf)
[response_32_43.pdf](https://github.com/jpata/cmssw/files/3168424/response_32_43.pdf)

**Comment by jpata** [comment]
Hi @hatakeyamak @bendavid @guitargeek @juska
I was wondering if you have any comments on the PFAlgo refactoring. Was not sure now what the PF group plans for this, I will have some time to work on it this week if we know the direction we want to take. Should I just make a PR against central CMSSW perhaps and see if there are comments there?

**Comment by hatakeyamak** [comment]
Thanks @jpata.

As I wrote earlier, I think I prefer to do this after @guitargeek first makes the cleanup of legacy PF electron and photon code, making sure we remove this in a way it is transparent to all offline and HLT. This reshuffling is a big one, and still thinking if introducing all these functions (and its naming convention) makes sense. And, I think the transition will go smoother in terms of review etc, if we do the restructure after the cleanup (than the other way around). What do you think?

@guitargeek, am I correct that you are ready to go as soon as 10_7_X or 11_0_X branch opens up?

By the way, this branch name makes me wonder if you are still working on 10_5. I think several changes were made made on PFAlgo since then, so you may have to do rebase. Do you see that your branch is mergeable to cmssw's head?

**Comment by jpata** [comment]
Fine.

**Comment by hatakeyamak** [comment]
Well, that's my personal opinion and I am curious what others think.

And, I do plan to look at how introduced new functions.

**Comment by jpata** [comment]
They do need to go in steps for purely technical reasons, but I don't see that the core PFAlgo is being modified in cms-sw#26658.

**Comment by hatakeyamak** [comment]
Okay. I will be having a closer look by the end of the week, but try to be sooner.

**Comment by jpata** [comment]
@hatakeyamak to clarify my earlier point, in https://github.com/cms-sw/cmssw/compare/master...guitargeek:remove_egamma_pf_legacy the PFAlgo::processBlock is not modified, hence it would be independent of this refactoring.

I'm trying to find a concrete way to implement what we discussed last Tuesday but I'm open to suggestions. I simply thought I would tackle the core PF head-on, I'm fine to jump in in another spot, too. If it's too time consuming to review these changes for you here, I can make a PR directly against cmssw master, I just figured I'd get early feedback from you and @bendavid if this is the way you want to go. If it will help, I can compile the changes here to a set of slides for Tuesday.

**Comment by guitargeek** [comment]
Hi! Sorry for chiming in so late. You are right @hatakeyamak, I see that this PR would have to be rebased onto master anyway. Might even be that it does not interfere with the egamma removal then! You can try it out @jpata, my PR https://github.com/cms-sw/cmssw/pull/26813 is not open so you can take that branch and try to merge.

I think it would be simpler to review this after the egamma removal is merged. I tried to keep it minimal so I hope it won't take too long :)

**Comment by guitargeek** [comment]
Also it's not easy to compare because one needs to factor out the code formatting. Is there a way to compare this directly against the commit with only the code format, or would we need another branch for that?

**Comment by jpata** [comment]
@guitargeek generally diff does get confused one way or another if large parts of the code are moved around in the same file, even if the underlying code is not changed.
I simply have moved sections from PFAlgo::processBlock to standalone functions without modifying them.

**Comment by jpata** [comment]
I made all the changes in separate commits, so you can see e.g. here https://github.com/jpata/cmssw/pull/44/commits/9583b1a258608ab83d6856e38a5516ca176c3a8f only refactoring the photon part.

**Comment by guitargeek** [comment]
Ah ok nice, I see it's very easy to follow commit by commit, so thanks for doing it like that! I should take a look again tomorrow a bit more awake but so far that looks like a good initiative to me! Just one thing already that would for sure come up in the cmssw review: in CMSSW, function names have to start lower case.

**Comment by jpata** [comment]
thanks for any feedback @guitargeek, sure, function names are easy to change once you have functions 😉

An example where the diff returns something useful is: https://github.com/jpata/cmssw/pull/44/commits/c8b86ed04f3e4c51f992835bf390d9597577a1b2

Unfortunately, you won't be able to clearly see in the diff the electron loop, as the whole electron loop is very long, so the github interface won't return useful results: https://github.com/jpata/cmssw/pull/44/commits/cb80b6ed79b0ba141dfaadb49ca306cc67364237

My whole idea with this PR is to see if the PF-interested people are on the same page on how to go forward with the actual code refactoring and to make a concrete proposal. If this is not what you have in mind, we have to go back to the drawing board and come up with something concrete that we can work on. Hoping to hear your thoughts @hatakeyamak @bendavid!

**Comment by hatakeyamak** [comment]
> I can compile the changes here to a set of slides for Tuesday.

I think this will be useful.

**Comment by guitargeek** [comment]
Hi Joosep, sorry it's not really easy to review these large scale structural changes, gauging wether this structure you suggest is good either a) would require a lot of foresight and discussion or b) the courage to just go for it and see where it leads us. I advocate b).

I looked over the changes and honestly don't have any criticism which would be appropriate at this point. Of course that is not the end at the story, but I really think the first refactoring PR should not do much more than reformatting with clang-format and basic restructuring as you did. This reduces the room for mistakes significantly and after having a good structure/formatting, more further more targeted changes can be made and compared better. You say it very well in your preliminary slides:

"Does not change the functionality of the PF algo, but allows further refactoring based on function inputs and outputs"

Probably the structure you give to it will not remain final, and a few functions like `EleLoop1` have still cryptic names to me. But others are like `conversionAlgo` have very good names and scopes, so it's definitely a step in the right direction.

To summarize, I suggest to not loose much though on this refactoring as it's hard to estimate which changes make the most sense in the long run. But we have to start somewhere and this is for sure the right direction, so thanks a lot for the courage to reshuffle everything!

I really think we should keep up this ambitious pace and simply:
1) rebase all of these changes on master once https://github.com/cms-sw/cmssw/pull/26813 is merged
2) do everything done here in one CMSSW PR, probably just by changing this one: https://github.com/cms-sw/cmssw/pull/26825. In my opinion, having all the commits here PRed separately would be too slow :)

Sorry for the lack of technical arguments in this bla-bla post, but I think the time for them will come more once the changes suggested here are implemented in CMSSW.

**Comment by jpata** [comment]
Thanks for your thoughts @guitargeek. I agree with all of your points. I didn't spend too much time at this stage to think about the perfect function names or what parts will be needed in the future, this can be addressed.

Let's see how the PR review goes for cms-sw#26825, I'm happy to rebase once your changes are in.

Then, we can make a bigger PR with the rest of the changes.

**Comment by hatakeyamak** [comment]
Yeah, conversionAlgo and HFalgo, I thought it's a good naming. For others, I thought they can be named better, but I don't have concrete suggestions yet.

Basically, @guitargeek is removing usePFPhgton (and use usePFElectron) In cms-sw#26825, so after it's merged, the function for usePFPhgton won't be necessary, I think, but let's see how things go.

**Comment by jpata** [comment]
I agree EleLoop1 is not a great name. It simply contains the thousand-line loop:

https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFAlgo.cc#L1593
~~~
for(unsigned iEle=0; iEle<elements.size(); iEle++) {
...
} // end of loop 1 on elements iEle of any type
~~~
Probably as we break it apart further (we should!), we will understand what it does and be able to give a descriptive name that respects CMSSW conventions.

**Comment by hatakeyamak** [comment]
I think you just want to rebase to the current master for this to reflect the cleanup @guitargeek made recently. Thanks.

**Comment by jpata** [comment]
New CMSSW PR here: https://github.com/cms-sw/cmssw/pull/26894

**Comment by hatakeyamak** [comment]
Thank you @jpata .

https://github.com/cms-sw/cmssw/pull/26894
concluded. Do you plan to proceed with other planned refactoring pull requests?

You might consider some suggestions made during the previous PR in the next one as well.

Thanks a lot!

**Comment by jpata** [comment]
Thanks @hatakeyamak. Yes, I will now proceed this week with another iteration. Let's keep this PR here around until then, so I have a reference to look at.

**Comment by hatakeyamak** [comment]
Sounds good!

**Comment by jpata** [comment]
PR https://github.com/cms-sw/cmssw/pull/27153 was merged, so we can close this one.

**Pull request closed without merging**
