### PR TITLE
PF validation master PR

### PR DESCRIPTION
**Pull request by jpata**
All the changes between cms-sw/cmssw/master and the latest PF validation branch. Things still to do before making a PR in https://github.com/cms-sw/cmssw:

- [ ] validate against @juska's NanoAOD code (https://github.com/jpata/cmssw/issues/18)
- [ ] define L1-type offset observables in MinBias or NuGun events
- [ ] MET scale/resolution in Zmm 
- [ ] add additional validation samples (https://github.com/jpata/cmssw/issues/17)

Latest set of plots is available here: https://jpata.web.cern.ch/jpata/pfvalidation/2019_02_05/plots/

### CODE REVIEW

**Comment by jpata** [comment]
Updated plots with error calculation discussion from #18, PU vs noPU samples.
https://jpata.web.cern.ch/jpata/pfvalidation/2019_02_05/plots/

@hatakeyamak @juska have a look if you get a chance. This PR should be the "master thread" for finalizing the PF validation code.

**Comment by hatakeyamak** [comment]
Looks good to me! Thank you. It looks like some data points for resolution plots are a little scattered than they should, but it's hard to avoid I suppose.

Where do I find instruction to run make these plots and publish on some web page?

In JME meeting, they were testing the HCAL local reco change and its effect on JME variables. Probably we can run those samples (without and with HCAL local reco change) and see how things look in your plots?

https://its.cern.ch/jira/browse/PDMVRELVALS-4
have some details and we will write more details via email after one meeting.

**Comment by juska** [comment]
Hi all,

I managed to work thru the README.md and the full DQM sequence. There's a couple of small thinks that still needs attention so that the instructions are working out-of-the-box. Here's my log with some commentary:

`README.md:

l 15: ** The commands takes me home. Variable $CMSSW_BASE is not defined. **

l 21:
"
[juska@lxplus007 RecoParticleFlow]$ make QCD_reco
cd tmp2 && /src/Validation/RecoParticleFlow/test/run_relval.sh QCD reco 0
/bin/sh: line 0: cd: tmp2:

 No such file or directory
"


** I try again after mkdir tmp2: **


"
[juska@lxplus007 RecoParticleFlow]$ mkdir tmp2
[juska@lxplus007 RecoParticleFlow]$ 
[juska@lxplus007 RecoParticleFlow]$ make QCD_reco
cd tmp2 && /src/Validation/RecoParticleFlow/test/run_relval.sh QCD reco 0
/bin/sh: /src/Validation/RecoParticleFlow/test/run_relval.sh: No such file or directory
make: *** [QCD_reco] Error 127
"

** I set the $CMSSW_BASE variable to point to CMSSW_9_4_11/ and try again: **

"
[juska@lxplus007 CMSSW_9_4_11]$ export CMSSW_BASE=`pwd`
[juska@lxplus007 CMSSW_9_4_11]$ echo $CMSSW_BASE
/afs/cern.ch/user/j/juska/work/pfdev/feb5/CMSSW_9_4_11
[juska@lxplus007 CMSSW_9_4_11]$ cd src/Validation/RecoParticleFlow/
[juska@lxplus007 RecoParticleFlow]$ make QCD_reco
cd tmp2 && /afs/cern.ch/user/j/juska/work/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/run_relval.sh QCD reco 0
/afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/filelist_QCD.txt QCD RECO 0
Making subdirectory QCD
Running step RECO
...
"

** Working now! **

** Proceeding to DQM step **

[juska@lxplus091 RecoParticleFlow]$ make QCD_dqm 
rm -f tmp2/QCD/DQM*.root
cd tmp2 && /afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/run_relval.sh QCD dqm 0
/afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/filelist_QCD.txt QCD DQM 0
Running step DQM
step3 filenames for DQM: 


** I don't know what to reply, I'll try to give whatever has appeared to tmp2 **


[juska@lxplus091 RecoParticleFlow]$ make QCD_dqm 
rm -f tmp2/QCD/DQM*.root
cd tmp2 && /afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/run_relval.sh QCD dqm 0
/afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/filelist_QCD.txt QCD DQM 0
Running step DQM
step3 filenames for DQM: 
/afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/tmp2/QCD/step3.root
/afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/tmp2/QCD/step3.root


 ** I thought it does not work, but it did something after waiting for some 20 seconds! **
 ** Not sure if my input really affected anything? **
 
 ** I proceed to QCD_post... **
 
 [juska@lxplus091 RecoParticleFlow]$ make QCD_post
rm -f tmp2/QCD/*withResponse.root tmp2/QCD/DQMTotal.root
cd tmp2 && python /afs/cern.ch/work/j/juska/pfdev/feb5/CMSSW_9_4_11/src/Validation/RecoParticleFlow/test/addResponse.py QCD/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
.
.
.

** All good! Now the final plotting... **


[juska@lxplus091 RecoParticleFlow]$ make plots
rm -Rf plots	
python test/compare.py --sample FlatQCD:tmp2/QCD/DQMTotal.root:tmp2/QCD/DQMTotal.root \
	--doResponsePlots
.
.
.

** Worked just fine, wuhuu!! **`

**Comment by jpata** [comment]
@Juska, I didn't mean to merge this PR. This was meant to track all changes between CMSSW master and our developments before we make an official PR. Sorry if that wasn't clear.

**Pull request merged**
